### ISSUE TITLE
Any results on real life known people?

### ISSUE THREAD

**Issue by Neltherion** [royorel/Lifespan_Age_Transformation_Synthesis#13]
Are there any tests done on real life known people to estimate the relative accuracy of this work? For example giving images of a baby from 2000s and estimating his/her face now and comparing it to the person grown up now?

Thanks

**Comment by royorel** [comment]
The test you suggest is very tricky. You can never have a reference image with the exact same lighting, pose, expression, hairstyle etc. These differences will bias any known metric, including human evaluation. In addition, there are many environmental aspects related to how a person ages that our algorithm doesn't take into account, like whether the person is smoking, the person's health condition, dietary habits and so forth. To conclude, as we have stated in the readme file, the algorithm is designed to produce an approximation of a person's appearance, not predicting the exact appearance at each age.   

With that said, since the full code is available, you can easily run this kind of experiment. The "Generate Full Progression" section in the readme file explains how to generate still images for the anchor classes.
