### ISSUE TITLE
Training data arrangement

### ISSUE THREAD

**Issue by arshagarwal** [royorel/Lifespan_Age_Transformation_Synthesis#14]
While training the model on some other face-aging dataset from scratch, how does the model expect the dataset arrangement to be?
More specifically, what should be the arrangement of folders in the "dataroot" folder?
It would be great if you could add that in the ReadMe, because it seems really difficult to figure that out through the data loader code.

Ps: Thanks for the great research. @royorel

**Comment by royorel** [comment]
Hi @arshagarwal, 

take a look at `datasets/create_dataset.py`. It takes the labeled, but unordered raw FFHQ-Aging dataset and order it in the desired structure which is:
```                                                                                           
├── dataset_name                                                                                                                                                                                                       
│   ├── train<class1> 
|   |   └── image1.png
|   |   └── image2.png
|   |   └── ...                                                                                                
│   │   ├── parsings
│   │   │   └── image1.png
│   │   │   └── image2.png
│   │   │   └── ...                                                                                                                             
...
│   ├── train<classN> 
|   |   └── image1.png
|   |   └── image2.png
|   |   └── ...                                                                                                
│   │   ├── parsings
│   │   │   └── image1.png
│   │   │   └── image2.png
│   │   │   └── ... 
...
│   ├── test<class1> 
|   |   └── image1.png
|   |   └── image2.png
|   |   └── ...                                                                                                
│   │   ├── parsings
│   │   │   └── image1.png
│   │   │   └── image2.png
│   │   │   └── ...                                                                                                                             
...
│   ├── test<classN> 
|   |   └── image1.png
|   |   └── image2.png
|   |   └── ...                                                                                                
│   │   ├── parsings
│   │   │   └── image1.png
│   │   │   └── image2.png
│   │   │   └── ... 

``` 

Image names don't need to have any pattern, but parsings image names should match their corresponding image name.
I will add this explanation to the readme file.

Please let me know if you have further questions.

**Comment by arshagarwal** [comment]
Thanks for the answer @royorel. Can you also explain how can we train on some other face-aging dataset (say CACD for example), for which we have only age labels corresponding to an image and not any other information as used in the "datasets/create_dataset.py" file?

**Comment by royorel** [comment]
These parameters are used to prune images, if you want to train on a different dataset here are the necessary actions to take:
1. The parsing maps can be obtained by running the provided the DeepLab network face segmentation network on your dataset.
2. Acquire the missing labels: You can get the head pose angles, eye occlusion and glasses type using any online face recognition services (we used face++, but I'm sure you can get these labels from other services as well).  The only missing thing will be the age and gender confidence values, we got these as part of our labeling efforts. I don't remember if CACD has confidence labels or not. If it doesn't you would have to trust the given labels and not use the label confidence value in the pruning algorithm.
  
Two extra things to keep in mind:
1. You can add or remove pruning criteria and/or change threshold values, we used what looked reasonable for us to prune, you might think otherwise.
2. Old celebrity datasets like CACD (and probably CelebA too) violate copyrights, since the original images belong to photo agencies like Getty Images, Shutterstock, Adobe Stock etc. Publishing these photos in a paper is risky.

**Comment by arshagarwal** [comment]
Thanks for the answer, this helps a lot.
