### ISSUE TITLE
why ValueError: not enough values to unpack (expected 10, got 7)

### ISSUE THREAD

**Issue by lvxueqi666** [royorel/Lifespan_Age_Transformation_Synthesis#36]
hi， I run the code on the linux, there's some issues

<img width="716" alt="1679968944267" src="https://user-images.githubusercontent.com/33738241/228107777-7d196518-3316-4a38-8e3c-cb10efa79085.png">

**Comment by royorel** [comment]
@lvxueqi666 

can you give some details on what mode did you ran the code in? This should not happen.

In addition, what is train_distan.py? This file is not part of the original repository.

**Comment by lvxueqi666** [comment]
I unzipped the compressed package of the code on the remote server, and then prepared the dataset and put it in the corresponding directory.
But I didn't download the pre-trained model. 
I found that in train.sh file, it was train.py but there was no file, only train_distan.shSo I modified it.
Then I ran ./run_scripts/train.sh and reported that error.

<img width="1156" alt="1680006874650" src="https://user-images.githubusercontent.com/33738241/228237484-930c7dc0-711c-4611-a0e4-16ff92b9e68d.png">

**Comment by royorel** [comment]
I'm not sure where these files are coming from. If you browse the files in the repository, you won't find these files.

Regardless, the error message indicates that the output line expects 10 output variables but the function only returns 7. Probably because it runs in a different mode then expected. You can figure out which variables are not returned and adjust accordingly.

**Comment by lvxueqi666** [comment]
sorry，  I found that I download the code from “https://github.com/SenHe/DLFS”  .
The author of the code saied follow your preparation. 
So I followed your  README to prepare my work.
Sorry to bother you, thank you very much!
