### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by DaddyWesker** [royorel/Lifespan_Age_Transformation_Synthesis#8]
Hello! 

I've been trying to just run script on my machine and got out of memory error. Thing is, that i've tried to run it on 1080 ti with 11 gb free VRAM. What kind of graphics card needed to run this? Is there any solution to run script on current 1080ti?

**Comment by stone100010** [comment]
在colab里面玩吧，你显卡运行不起来

**Comment by royorel** [comment]
Hello, 

Is there some memory issue with the Colab?
If so, can you please describe it in English?

**Comment by stone100010** [comment]
Colab should have no problems. If you can reply to me, I will be happy to help you correct colab running errors. Please remember to contact me.

**Comment by stone100010** [comment]
我在colab里面运行了，上传了我自己的图片，但是表现效果并没有达到我的预期，实在是抱歉。

**Comment by amittal27** [comment]
> Colab should have no problems. If you can reply to me, I will be happy to help you correct colab running errors. Please remember to contact me.

Hi, I am currently experiencing this issue on colab. How can I mitigate it?

**Comment by royorel** [comment]
Hi @amittal27,

Can you please describe what exactly is the issue?
Is it out of memory error on colab?

**Comment by amittal27** [comment]
@royorel , it has been happening when I change the class groups to suit my needs for my own research project. 

I've changed the CLASSES_UPPER_BOUNDS variable to be [1, 3, 5, 8, 11, 14, 17, 25, 35] and have also updated the opt.sort_order option to generate a full progression of images between these age ranges. However, I receive the CUDA out of memory error in colab when I make these changes.

Am I supposed to be changing other variables as well in order to generate images in the desired age ranges?

Thank you!

**Comment by royorel** [comment]
@amittal27,

There are two issues with what you describe:

1. First, I don't think there's a way to control what kind of GPU colab will allocate. Sometimes I also get out of memory error, even though I tested all the default parameters on colab and they worked. the way to solve this is to slightly increase `opt.interp_step`:
![image](https://user-images.githubusercontent.com/13196935/130340804-398795f6-feda-421d-b222-a16abbf211cf.png)

Usually increasing it to 0.06 is enough, but if i's still not working keep increasing the number by 0.01 until it works.

2. You both changed the age groups boundaries, and increased the number of age groups. The pre-trained model was trained on a dataset for exactly 6 age groups with these specific boundaries. Changing CLASSES_UPPER_BOUNDS will corrupt the results since you basically define new age groups that the model never saw.  **The results from the paper cannot be replicated with this change**. In addition, increasing the number of age groups also increases the number of outputs the GPU has to create in parallel, which will in turn lead to an out of memory error, the solution here is the same as above, increase `opt.interp_step`

**Comment by amittal27** [comment]
@royorel ,

Thank you for the clarification. I've been increasing the opt.interp_step, which has definitely helped with the issue described. 

In terms of the age group boundaries, I'm then thinking that I could figure out the general ages of the interpolated images between the 6 anchor age groups. I was reading your paper attached to the repo and was wondering what alpha represented in this formula:

![image](https://user-images.githubusercontent.com/25964997/130341167-87d39eb9-fa05-4a01-ab91-4406b383b2bf.png)

Is this the interpolation step or the fractional placement of the image between consequent age groups? For example, if opt.interp_step = 0.25 such that 3 images are interpolated between the anchor groups, would alpha = 0.25 represent the first image of the three and 0.5 the middle one?

**Comment by royorel** [comment]
@amittal27 

Alpha is indeed the interpolation step. I would say it is safe to assume that the image generated from an alpha vale of 0.75 will have an appearance that is slightly older than the appearance of an image generated from an alpha value of 0.5 for instance, but I wouldn't draw any conclusion beyond that. 

The interpolation is meant to simulate the aging effect in a continuous way. However, the interpolated images do not directly correspond to a specific age. We didn't claim anything in the paper regarding the correspondence of the interpolated images to any specific age.
